name: Setup Fortran with Conda
description: Installs Fortran compilers and extra packages using Conda. Optionally builds and deploys FORD and/or Doxygen docs.
author: Seyed Ali Ghasemi
branding:
  icon: check
  color: purple

inputs:
  compiler:
    description: "Fortran compiler to install (gfortran, ifx, lfortran, flang)"
    required: false
    default: ""
  compiler-version:
    description: "compiler version"
    required: false
    default: ""
  platform:
    description: "Runner OS platform (ubuntu-latest, windows-latest, macos-latest)"
    required: false
    default: ""
  extra-packages:
    description: "List of additional Conda packages (e.g., cmake ninja)"
    required: false
    default: ""
  fpm-version:
    description: "Optional fpm version. Empty means latest."
    required: false
    default: ""
  checkout-repo:
    description: "Whether to checkout the repository before setup"
    required: false
    default: "true"

  generate-doc-ford:
    description: "Whether to build and deploy FORD documentation"
    required: false
    default: "false"
  ford-config:
    description: "Path to FORD config file (e.g., README.md or ford.md)"
    required: false
    default: "README.md"
  ford-branch:
    description: "Branch to deploy FORD docs to"
    required: false
    default: "gh-pages-ford"
  ford-working-directory:
    description: "Directory to run FORD from (relative to root)"
    required: false
    default: "."
  ford-output-directory:
    description: "Path to generated FORD documentation (used by deployment)"
    required: false
    default: "doc/ford"
  ford-target-folder:
    description: "Target folder in repo for deployed FORD docs"
    required: false
    default: "doc/ford"

  generate-doc-doxygen:
    description: "Whether to build and deploy Doxygen documentation"
    required: false
    default: "false"
  doxygen-config:
    description: "Path to Doxygen config file (e.g., Doxyfile)"
    required: false
    default: "Doxyfile"
  doxygen-branch:
    description: "Branch to deploy Doxygen docs to"
    required: false
    default: "gh-pages-doxygen"
  doxygen-working-directory:
    description: "Directory to run Doxygen from (relative to root)"
    required: false
    default: "."
  doxygen-output-directory:
    description: "Path to generated Doxygen documentation (used by deployment)"
    required: false
    default: "doc/doxygen"
  doxygen-target-folder:
    description: "Target folder in repo for deployed Doxygen docs"
    required: false
    default: "doc/doxygen"

  generate-status-fpm:
    description: "Generate STATUS.md for fpm jobs"
    required: false
    default: "false"
  generate-status-cmake:
    description: "Generate STATUS.md for cmake jobs"
    required: false
    default: "false"
  generate-status-meson:
    description: "Generate STATUS.md for meson jobs"
    required: false
    default: "false"

  update-readme-table:
    description: "Auto-update the status table in README.md and open a PR"
    required: false
    default: "false"
  update-readme-user-name:
    description: "Git user.name for README.md update commit"
    required: false
    default: ""
  update-readme-user-email:
    description: "Git user.email for README.md update commit"
    required: false
    default: ""
  update-readme-token:
    description: "Token used by create-pull-request"
    required: false
    default: ""

  fortitude-check:
    description: "Run Fortitude check"
    required: false
    default: "false"
  fortitude-settings:
    description: "Extra flags for 'fortitude check'"
    required: false
    default: "--output-format github"

runs:
  using: composite
  steps:
    - name: Checkout repository
      if: ${{ inputs.checkout-repo == 'true'
        || inputs.generate-doc-ford == 'true'
        || inputs.generate-doc-doxygen == 'true'
        || inputs.generate-status-fpm == 'true'
        || inputs.generate-status-cmake == 'true'
        || inputs.generate-status-meson == 'true'
        || inputs.update-readme-table == 'true' }}
      uses: actions/checkout@v4

    - name: Decide whether Conda is needed
      shell: bash
      run: |
        set -euo pipefail
        need_conda="false"
        if [[ -n "${{ inputs.compiler }}" && -n "${{ inputs.platform }}" ]]; then need_conda="true"; fi
        if [[ "${{ inputs.generate-doc-ford }}" == "true" || "${{ inputs.generate-doc-doxygen }}" == "true" ]]; then need_conda="true"; fi
        if [[ "${{ inputs.fortitude-check }}" == "true" ]]; then need_conda="true"; fi
        echo "NEED_CONDA=$need_conda" >> "$GITHUB_ENV"

    - name: Setup Miniconda
      if: ${{ env.NEED_CONDA == 'true' }}
      uses: conda-incubator/setup-miniconda@v3.3.0
      with:
        auto-update-conda: false
        activate-environment: fortran
        channels: conda-forge, defaults

    - name: Run compiler setup
      id: sfc_setup
      if: ${{ inputs.compiler != '' && inputs.platform != '' && env.NEED_CONDA == 'true' }}
      shell: bash
      env:
        INPUT_COMPILER: ${{ inputs.compiler }}
        INPUT_COMPILER_VERSION: ${{ inputs.compiler-version }}
        INPUT_PLATFORM: ${{ inputs.platform }}
        INPUT_EXTRA_PACKAGES: ${{ inputs.extra-packages }}
        INPUT_FPM_VERSION: ${{ inputs.fpm-version }}
      run: |
        set -euo pipefail
        node "${{ github.action_path }}/index.js"

    - name: Upload version JSON artifact
      if: ${{ inputs.compiler != '' && inputs.platform != '' && env.NEED_CONDA == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: sfc-${{ github.job }}-${{ runner.os }}-${{ inputs.compiler }}-${{ steps.sfc_setup.outputs.version || 'unknown' }}-${{ github.run_id }}
        path: ${{ runner.temp }}/sfc_versions/*.json
        if-no-files-found: ignore
        retention-days: 7

    - name: Fortitude
      if: ${{ inputs.fortitude-check == 'true' && env.NEED_CONDA == 'true' }}
      shell: bash
      run: |
        set -euo pipefail
        eval "$(conda shell.bash hook)"
        conda activate fortran
        pip install fortitude-lint
        fortitude check ${{ inputs.fortitude-settings }}

    - name: Build FORD docs
      if: ${{ inputs.generate-doc-ford == 'true' && env.NEED_CONDA == 'true' }}
      shell: bash
      run: |
        set -euo pipefail
        eval "$(conda shell.bash hook)"
        conda activate fortran
        conda install -y pip graphviz
        pip install ford
        mkdir -p "${{ inputs.ford-output-directory }}"
        cd "${{ inputs.ford-working-directory }}"
        ford "${{ inputs.ford-config }}"

    - name: Deploy FORD docs
      if: ${{ inputs.generate-doc-ford == 'true' }}
      uses: JamesIves/github-pages-deploy-action@v4.8.0
      with:
        branch: ${{ inputs.ford-branch }}
        folder: ${{ inputs.ford-output-directory }}
        target-folder: ${{ inputs.ford-target-folder }}
        clean: ${{ !contains('main master', inputs.ford-branch) }}
        commit-message: Deploy FORD docs

    - name: Build Doxygen docs
      if: ${{ inputs.generate-doc-doxygen == 'true' && env.NEED_CONDA == 'true' }}
      shell: bash
      run: |
        set -euo pipefail
        eval "$(conda shell.bash hook)"
        conda activate fortran
        conda install -y graphviz doxygen
        mkdir -p "${{ inputs.doxygen-output-directory }}"
        cd "${{ inputs.doxygen-working-directory }}"
        doxygen "${{ inputs.doxygen-config }}"

    - name: Deploy Doxygen docs
      if: ${{ inputs.generate-doc-doxygen == 'true' }}
      uses: JamesIves/github-pages-deploy-action@v4.8.0
      with:
        branch: ${{ inputs.doxygen-branch }}
        folder: ${{ inputs.doxygen-output-directory }}
        target-folder: ${{ inputs.doxygen-target-folder }}
        clean: ${{ !contains('main master', inputs.doxygen-branch) }}
        commit-message: Deploy Doxygen docs

    - name: Download version artifacts (STATUS.md)
      if: ${{ inputs.generate-status-fpm == 'true' || inputs.generate-status-cmake == 'true' || inputs.generate-status-meson == 'true' }}
      uses: actions/download-artifact@v4
      with:
        pattern: sfc-*
        path: ${{ runner.temp }}/sfc_status/sfc_versions

    - name: Generate STATUS.md (fpm)
      if: ${{ inputs.generate-status-fpm == 'true' }}
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        REPO: ${{ github.repository }}
        RUN_ID: ${{ github.run_id }}
        VERSIONS_DIR: ${{ runner.temp }}/sfc_status/sfc_versions
      run: |
        set -euo pipefail
        bash "${{ github.action_path }}/scripts/generate-status-md.sh" fpm

    - name: Deploy STATUS.md (fpm)
      if: ${{ inputs.generate-status-fpm == 'true' }}
      uses: JamesIves/github-pages-deploy-action@v4.8.0
      with:
        branch: status-fpm
        folder: status-fpm
        clean: true
        commit-message: Deploy fpm status

    - name: Generate STATUS.md (cmake)
      if: ${{ inputs.generate-status-cmake == 'true' }}
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        REPO: ${{ github.repository }}
        RUN_ID: ${{ github.run_id }}
        VERSIONS_DIR: ${{ runner.temp }}/sfc_status/sfc_versions
      run: |
        set -euo pipefail
        bash "${{ github.action_path }}/scripts/generate-status-md.sh" cmake

    - name: Deploy STATUS.md (cmake)
      if: ${{ inputs.generate-status-cmake == 'true' }}
      uses: JamesIves/github-pages-deploy-action@v4.8.0
      with:
        branch: status-cmake
        folder: status-cmake
        clean: true
        commit-message: Deploy cmake status

    - name: Generate STATUS.md (meson)
      if: ${{ inputs.generate-status-meson == 'true' }}
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        REPO: ${{ github.repository }}
        RUN_ID: ${{ github.run_id }}
        VERSIONS_DIR: ${{ runner.temp }}/sfc_status/sfc_versions
      run: |
        set -euo pipefail
        bash "${{ github.action_path }}/scripts/generate-status-md.sh" meson

    - name: Deploy STATUS.md (meson)
      if: ${{ inputs.generate-status-meson == 'true' }}
      uses: JamesIves/github-pages-deploy-action@v4.8.0
      with:
        branch: status-meson
        folder: status-meson
        clean: true
        commit-message: Deploy meson status

    - name: Download version artifacts (README update)
      if: ${{ inputs.update-readme-table == 'true' }}
      uses: actions/download-artifact@v4
      with:
        pattern: sfc-*
        path: ${{ runner.temp }}/sfc_ci/sfc_versions

    - name: Aggregate versions
      if: ${{ inputs.update-readme-table == 'true' }}
      shell: bash
      run: |
        set -euo pipefail
        node "${{ github.action_path }}/scripts/aggregate-versions.js" \
          "${{ runner.temp }}/sfc_ci/sfc_versions" \
          "${{ runner.temp }}/sfc_ci/versions.json"

    - name: Fetch job results
      if: ${{ inputs.update-readme-table == 'true' }}
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        REPO: ${{ github.repository }}
        RUN_ID: ${{ github.run_id }}
      run: |
        set -euo pipefail
        mkdir -p "${{ runner.temp }}/sfc_ci"
        curl -fsSL -H "Authorization: token $GH_TOKEN" \
          "https://api.github.com/repos/$REPO/actions/runs/$RUN_ID/jobs?per_page=200" \
          > "${{ runner.temp }}/sfc_ci/jobs.json"

    - name: Update README table
      if: ${{ inputs.update-readme-table == 'true' }}
      shell: bash
      env:
        JOBS_FILE: ${{ runner.temp }}/sfc_ci/jobs.json
        VERSIONS_FILE: ${{ runner.temp }}/sfc_ci/versions.json
      run: |
        set -euo pipefail
        bash "${{ github.action_path }}/scripts/update-readme-status.sh"

    - name: Setup Git author
      if: ${{ inputs.update-readme-table == 'true' }}
      shell: bash
      run: |
        set -euo pipefail
        git config user.name "${{ inputs.update-readme-user-name }}"
        git config user.email "${{ inputs.update-readme-user-email }}"

    - name: Create PR
      if: ${{ inputs.update-readme-table == 'true' }}
      uses: peter-evans/create-pull-request@v8.1.0
      with:
        token: ${{ inputs.update-readme-token }}
        commit-message: "Update README.md status table [ci skip]"
        branch: update/readme-status-table
        title: "update README.md status table"
        body: "This PR updates the CI status table in the README.md."
        delete-branch: true