name: BLAS/LAPACK CI

on:
  push:
    branches: [main, dev]
    paths:
      - ".github/workflows/blas_lapack.yml"
      - "action.yml"
      - "src/**"
      - "dist/**"
      - "package.json"
      - "package-lock.json"
      - "tests/blas_lapack/**"
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/blas_lapack.yml"
      - "action.yml"
      - "src/**"
      - "dist/**"
      - "package.json"
      - "package-lock.json"
      - "tests/blas_lapack/**"
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  test_fpm:
    name: ${{ matrix.os }}_${{ matrix.compiler }}_${{ matrix.backend }}_fpm
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - {os: ubuntu-latest,  compiler: gfortran,  backend: netlib,        extra-packages: "blas-devel=*=*_netlib",        fpm-version: ""}
        - {os: ubuntu-latest,  compiler: gfortran,  backend: openblas,      extra-packages: "blas-devel=*=*_openblas",      fpm-version: ""}
        - {os: ubuntu-latest,  compiler: gfortran,  backend: mkl,           extra-packages: "blas-devel=*=*_mkl",           fpm-version: ""}
        - {os: ubuntu-latest,  compiler: ifx,       backend: netlib,        extra-packages: "blas-devel=*=*_netlib",        fpm-version: ""}
        - {os: ubuntu-latest,  compiler: ifx,       backend: openblas,      extra-packages: "blas-devel=*=*_openblas",      fpm-version: ""}
        - {os: ubuntu-latest,  compiler: ifx,       backend: mkl,           extra-packages: "blas-devel=*=*_mkl",           fpm-version: ""}
        - {os: ubuntu-latest,  compiler: lfortran,  backend: mkl,           extra-packages: "blas-devel=*=*_mkl",           fpm-version: "0.12.0"}
        - {os: ubuntu-latest,  compiler: flang,     backend: netlib,        extra-packages: "blas-devel=*=*_netlib",        fpm-version: ""}
        - {os: ubuntu-latest,  compiler: flang,     backend: openblas,      extra-packages: "blas-devel=*=*_openblas",      fpm-version: ""}
        - {os: ubuntu-latest,  compiler: flang,     backend: mkl,           extra-packages: "blas-devel=*=*_mkl",           fpm-version: ""}
        - {os: ubuntu-latest,  compiler: flang-new, backend: netlib,        extra-packages: "blas-devel=*=*_netlib",        fpm-version: ""}
        - {os: ubuntu-latest,  compiler: flang-new, backend: openblas,      extra-packages: "blas-devel=*=*_openblas",      fpm-version: ""}
        - {os: ubuntu-latest,  compiler: flang-new, backend: mkl,           extra-packages: "blas-devel=*=*_mkl",           fpm-version: ""}
        - {os: ubuntu-latest,  compiler: nvfortran, backend: netlib,        extra-packages: "blas-devel=*=*_netlib",        fpm-version: ""}
        - {os: ubuntu-latest,  compiler: nvfortran, backend: openblas,      extra-packages: "blas-devel=*=*_openblas",      fpm-version: ""}
        - {os: ubuntu-latest,  compiler: nvfortran, backend: mkl,           extra-packages: "blas-devel=*=*_mkl",           fpm-version: ""}
        - {os: ubuntu-latest,  compiler: aocc,      backend: netlib,        extra-packages: "blas-devel=*=*_netlib",        fpm-version: ""}
        - {os: ubuntu-latest,  compiler: aocc,      backend: openblas,      extra-packages: "blas-devel=*=*_openblas",      fpm-version: ""}
        - {os: ubuntu-latest,  compiler: aocc,      backend: mkl,           extra-packages: "blas-devel=*=*_mkl",           fpm-version: ""}
        - {os: ubuntu-latest,  compiler: aomp,      backend: netlib,        extra-packages: "blas-devel=*=*_netlib",        fpm-version: ""}
        - {os: ubuntu-latest,  compiler: aomp,      backend: openblas,      extra-packages: "blas-devel=*=*_openblas",      fpm-version: ""}
        - {os: ubuntu-latest,  compiler: aomp,      backend: mkl,           extra-packages: "blas-devel=*=*_mkl",           fpm-version: ""}
        - {os: macos-latest,   compiler: gfortran,  backend: netlib,        extra-packages: "blas-devel=*=*_netlib",        fpm-version: ""}
        - {os: macos-latest,   compiler: gfortran,  backend: openblas,      extra-packages: "blas-devel=*=*_openblas",      fpm-version: ""}
        - {os: macos-26-intel, compiler: gfortran,  backend: mkl,           extra-packages: "blas-devel=*=*_mkl",           fpm-version: ""}
        - {os: macos-latest,   compiler: gfortran,  backend: accelerate,    extra-packages: "blas-devel=*=*_accelerate",    fpm-version: ""}
        - {os: macos-26-intel, compiler: lfortran,  backend: mkl,           extra-packages: "blas-devel=*=*_mkl",           fpm-version: "0.12.0"}
        - {os: windows-latest, compiler: gfortran,  backend: netlib,        extra-packages: "blas-devel=*=*_netlib",        fpm-version: ""}
        - {os: windows-latest, compiler: gfortran,  backend: openblas,      extra-packages: "blas-devel=*=*_openblas",      fpm-version: ""}
        - {os: windows-latest, compiler: gfortran,  backend: mkl,           extra-packages: "blas-devel=*=*_mkl",           fpm-version: ""}
        - {os: windows-latest, compiler: flang,     backend: netlib,        extra-packages: "blas-devel=*=*_netlib",        fpm-version: ""}
        - {os: windows-latest, compiler: flang,     backend: openblas,      extra-packages: "blas-devel=*=*_openblas",      fpm-version: ""}
        - {os: windows-latest, compiler: flang,     backend: mkl,           extra-packages: "blas-devel=*=*_mkl",           fpm-version: ""}
        - {os: windows-latest, compiler: flang-new, backend: netlib,        extra-packages: "blas-devel=*=*_netlib",        fpm-version: ""}
        - {os: windows-latest, compiler: flang-new, backend: openblas,      extra-packages: "blas-devel=*=*_openblas",      fpm-version: ""}
        - {os: windows-latest, compiler: flang-new, backend: mkl,           extra-packages: "blas-devel=*=*_mkl",           fpm-version: ""}

    steps:
      - name: Setup Fortran and BLAS/LAPACK
        uses: gha3mi/setup-fortran-conda@dev
        with:
          compiler: ${{ matrix.compiler }}
          extra-packages: ${{ matrix.extra-packages }}
          fpm-version: ${{ matrix.fpm-version }}

      - name: fpm BLAS/LAPACK test
        working-directory: tests/blas_lapack
        run: fpm test --compiler "${{ env.FPM_FC }}" --profile release --verbose

  test_cmake:
    name: ${{ matrix.os }}_${{ matrix.compiler }}_${{ matrix.backend }}_cmake
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - {os: ubuntu-latest,  compiler: gfortran,  backend: netlib,        extra-packages: "blas-devel=*=*_netlib"}
        - {os: ubuntu-latest,  compiler: gfortran,  backend: openblas,      extra-packages: "blas-devel=*=*_openblas"}
        - {os: ubuntu-latest,  compiler: gfortran,  backend: mkl,           extra-packages: "blas-devel=*=*_mkl"}
        - {os: ubuntu-latest,  compiler: ifx,       backend: netlib,        extra-packages: "blas-devel=*=*_netlib"}
        - {os: ubuntu-latest,  compiler: ifx,       backend: openblas,      extra-packages: "blas-devel=*=*_openblas"}
        - {os: ubuntu-latest,  compiler: ifx,       backend: mkl,           extra-packages: "blas-devel=*=*_mkl"}
        - {os: ubuntu-latest,  compiler: lfortran,  backend: mkl,           extra-packages: "blas-devel=*=*_mkl"}
        - {os: ubuntu-latest,  compiler: flang,     backend: netlib,        extra-packages: "blas-devel=*=*_netlib"}
        - {os: ubuntu-latest,  compiler: flang,     backend: openblas,      extra-packages: "blas-devel=*=*_openblas"}
        - {os: ubuntu-latest,  compiler: flang,     backend: mkl,           extra-packages: "blas-devel=*=*_mkl"}
        - {os: ubuntu-latest,  compiler: flang-new, backend: netlib,        extra-packages: "blas-devel=*=*_netlib"}
        - {os: ubuntu-latest,  compiler: flang-new, backend: openblas,      extra-packages: "blas-devel=*=*_openblas"}
        - {os: ubuntu-latest,  compiler: flang-new, backend: mkl,           extra-packages: "blas-devel=*=*_mkl"}
        - {os: ubuntu-latest,  compiler: nvfortran, backend: netlib,        extra-packages: "blas-devel=*=*_netlib"}
        - {os: ubuntu-latest,  compiler: nvfortran, backend: openblas,      extra-packages: "blas-devel=*=*_openblas"}
        - {os: ubuntu-latest,  compiler: nvfortran, backend: mkl,           extra-packages: "blas-devel=*=*_mkl"}
        - {os: ubuntu-latest,  compiler: aocc,      backend: netlib,        extra-packages: "blas-devel=*=*_netlib"}
        - {os: ubuntu-latest,  compiler: aocc,      backend: openblas,      extra-packages: "blas-devel=*=*_openblas"}
        - {os: ubuntu-latest,  compiler: aocc,      backend: mkl,           extra-packages: "blas-devel=*=*_mkl"}
        - {os: ubuntu-latest,  compiler: aomp,      backend: netlib,        extra-packages: "blas-devel=*=*_netlib"}
        - {os: ubuntu-latest,  compiler: aomp,      backend: openblas,      extra-packages: "blas-devel=*=*_openblas"}
        - {os: ubuntu-latest,  compiler: aomp,      backend: mkl,           extra-packages: "blas-devel=*=*_mkl"}
        - {os: macos-latest,   compiler: gfortran,  backend: netlib,        extra-packages: "blas-devel=*=*_netlib"}
        - {os: macos-latest,   compiler: gfortran,  backend: openblas,      extra-packages: "blas-devel=*=*_openblas"}
        - {os: macos-26-intel, compiler: gfortran,  backend: mkl,           extra-packages: "blas-devel=*=*_mkl"}
        - {os: macos-latest,   compiler: gfortran,  backend: accelerate,    extra-packages: "blas-devel=*=*_accelerate"}
        - {os: macos-26-intel, compiler: lfortran,  backend: mkl,           extra-packages: "blas-devel=*=*_mkl"}
        - {os: windows-latest, compiler: gfortran,  backend: netlib,        extra-packages: "blas-devel=*=*_netlib"}
        - {os: windows-latest, compiler: gfortran,  backend: openblas,      extra-packages: "blas-devel=*=*_openblas"}
        - {os: windows-latest, compiler: gfortran,  backend: mkl,           extra-packages: "blas-devel=*=*_mkl"}
        - {os: windows-latest, compiler: flang,     backend: netlib,        extra-packages: "blas-devel=*=*_netlib"}
        - {os: windows-latest, compiler: flang,     backend: openblas,      extra-packages: "blas-devel=*=*_openblas"}
        - {os: windows-latest, compiler: flang,     backend: mkl,           extra-packages: "blas-devel=*=*_mkl"}
        - {os: windows-latest, compiler: flang-new, backend: netlib,        extra-packages: "blas-devel=*=*_netlib"}
        - {os: windows-latest, compiler: flang-new, backend: openblas,      extra-packages: "blas-devel=*=*_openblas"}
        - {os: windows-latest, compiler: flang-new, backend: mkl,           extra-packages: "blas-devel=*=*_mkl"}

    steps:
      - name: Setup Fortran and BLAS/LAPACK
        uses: gha3mi/setup-fortran-conda@dev
        with:
          compiler: ${{ matrix.compiler }}
          extra-packages: ${{ matrix.extra-packages }}

      - name: CMake BLAS/LAPACK test
        working-directory: tests/blas_lapack
        run: |
          cmake -S . -B build/release -DCMAKE_BUILD_TYPE=Release -DCMAKE_Fortran_COMPILER="${{ env.CMAKE_Fortran_COMPILER }}" -G Ninja
          cmake --build build/release --config Release --verbose
          ctest --test-dir build/release --output-on-failure --no-tests=error --no-tests=error -VV

  test_meson:
    name: ${{ matrix.os }}_${{ matrix.compiler }}_${{ matrix.backend }}_meson
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - {os: ubuntu-latest,  compiler: gfortran,  backend: netlib,        extra-packages: "blas-devel=*=*_netlib"}
        - {os: ubuntu-latest,  compiler: gfortran,  backend: openblas,      extra-packages: "blas-devel=*=*_openblas"}
        - {os: ubuntu-latest,  compiler: gfortran,  backend: mkl,           extra-packages: "blas-devel=*=*_mkl"}
        - {os: ubuntu-latest,  compiler: ifx,       backend: netlib,        extra-packages: "blas-devel=*=*_netlib"}
        - {os: ubuntu-latest,  compiler: ifx,       backend: openblas,      extra-packages: "blas-devel=*=*_openblas"}
        - {os: ubuntu-latest,  compiler: ifx,       backend: mkl,           extra-packages: "blas-devel=*=*_mkl"}
        - {os: ubuntu-latest,  compiler: flang,     backend: netlib,        extra-packages: "blas-devel=*=*_netlib"}
        - {os: ubuntu-latest,  compiler: flang,     backend: openblas,      extra-packages: "blas-devel=*=*_openblas"}
        - {os: ubuntu-latest,  compiler: flang,     backend: mkl,           extra-packages: "blas-devel=*=*_mkl"}
        - {os: ubuntu-latest,  compiler: flang-new, backend: netlib,        extra-packages: "blas-devel=*=*_netlib"}
        - {os: ubuntu-latest,  compiler: flang-new, backend: openblas,      extra-packages: "blas-devel=*=*_openblas"}
        - {os: ubuntu-latest,  compiler: flang-new, backend: mkl,           extra-packages: "blas-devel=*=*_mkl"}
        - {os: ubuntu-latest,  compiler: nvfortran, backend: netlib,        extra-packages: "blas-devel=*=*_netlib"}
        - {os: ubuntu-latest,  compiler: nvfortran, backend: openblas,      extra-packages: "blas-devel=*=*_openblas"}
        - {os: ubuntu-latest,  compiler: nvfortran, backend: mkl,           extra-packages: "blas-devel=*=*_mkl"}
        - {os: ubuntu-latest,  compiler: aocc,      backend: netlib,        extra-packages: "blas-devel=*=*_netlib"}
        - {os: ubuntu-latest,  compiler: aocc,      backend: openblas,      extra-packages: "blas-devel=*=*_openblas"}
        - {os: ubuntu-latest,  compiler: aocc,      backend: mkl,           extra-packages: "blas-devel=*=*_mkl"}
        - {os: ubuntu-latest,  compiler: aomp,      backend: netlib,        extra-packages: "blas-devel=*=*_netlib"}
        - {os: ubuntu-latest,  compiler: aomp,      backend: openblas,      extra-packages: "blas-devel=*=*_openblas"}
        - {os: ubuntu-latest,  compiler: aomp,      backend: mkl,           extra-packages: "blas-devel=*=*_mkl"}
        - {os: macos-latest,   compiler: gfortran,  backend: netlib,        extra-packages: "blas-devel=*=*_netlib"}
        - {os: macos-latest,   compiler: gfortran,  backend: openblas,      extra-packages: "blas-devel=*=*_openblas"}
        - {os: macos-26-intel, compiler: gfortran,  backend: mkl,           extra-packages: "blas-devel=*=*_mkl"}
        - {os: macos-latest,   compiler: gfortran,  backend: accelerate,    extra-packages: "blas-devel=*=*_accelerate"}
        - {os: windows-latest, compiler: gfortran,  backend: netlib,        extra-packages: "blas-devel=*=*_netlib"}
        - {os: windows-latest, compiler: gfortran,  backend: openblas,      extra-packages: "blas-devel=*=*_openblas"}
        - {os: windows-latest, compiler: gfortran,  backend: mkl,           extra-packages: "blas-devel=*=*_mkl"}
        - {os: windows-latest, compiler: flang,     backend: netlib,        extra-packages: "blas-devel=*=*_netlib"}
        - {os: windows-latest, compiler: flang,     backend: openblas,      extra-packages: "blas-devel=*=*_openblas"}
        - {os: windows-latest, compiler: flang,     backend: mkl,           extra-packages: "blas-devel=*=*_mkl"}
        - {os: windows-latest, compiler: flang-new, backend: netlib,        extra-packages: "blas-devel=*=*_netlib"}
        - {os: windows-latest, compiler: flang-new, backend: openblas,      extra-packages: "blas-devel=*=*_openblas"}
        - {os: windows-latest, compiler: flang-new, backend: mkl,           extra-packages: "blas-devel=*=*_mkl"}

    steps:
      - name: Setup Fortran and BLAS/LAPACK
        uses: gha3mi/setup-fortran-conda@dev
        with:
          compiler: ${{ matrix.compiler }}
          extra-packages: ${{ matrix.extra-packages }}

      - name: Meson BLAS/LAPACK test
        working-directory: tests/blas_lapack
        run: |
          meson setup build/release . --buildtype release --backend=ninja
          meson compile -C build/release --verbose
          meson test -C build/release --verbose
