name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        compiler: [gfortran, ifx, lfortran, flang-new]
        include:
        - os: ubuntu-latest
          compiler: gfortran
          flag-debug: ""
          flag-release: ""
          extra-packages: ""
        - os: ubuntu-latest
          compiler: ifx
          flag-debug: ""
          flag-release: ""
          extra-packages: ""
        - os: ubuntu-latest
          compiler: lfortran
          flag-debug: ""
          flag-release: ""
          extra-packages: ""
        - os: ubuntu-latest
          compiler: flang-new
          flag-debug: ""
          flag-release: ""
          extra-packages: ""

        - os: macos-latest
          compiler: gfortran
          flag-debug: ""
          flag-release: ""
          extra-packages: ""
        - os: macos-latest
          compiler: lfortran
          flag-debug: ""
          flag-release: ""
          extra-packages: ""

        - os: windows-latest
          compiler: gfortran
          flag-debug: ""
          flag-release: ""
          extra-packages: ""
        - os: windows-latest
          compiler: ifx
          flag-debug: ""
          flag-release: ""
          extra-packages: ""
        - os: windows-latest
          compiler: lfortran
          flag-debug: ""
          flag-release: ""
          extra-packages: ""
        - os: windows-latest
          compiler: flang-new
          flag-debug: ""
          flag-release: ""
          extra-packages: ""

        exclude:
          - os: macos-latest
            compiler: flang-new
          - os: macos-latest
            compiler: ifx
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          activate-environment: fortran
          channels: conda-forge, defaults

      - name: Setup Fortran
        uses: gha3mi/setup-fortran-conda@dev
        with:
          compiler: ${{ matrix.compiler }}
          platform: ${{ matrix.os }}
          extra-packages: ${{ matrix.extra-packages }}

      - name: fpm test (debug)
        run: fpm test --compiler ${{ matrix.compiler }} --profile debug --flag "${{ matrix.flag-debug }}"  --verbose

      - name: fpm test (release)
        run: fpm test --compiler ${{ matrix.compiler }} --profile release --flag "${{ matrix.flag-release }}" --verbose