name: fpm status

on:
  workflow_call:

permissions:
  actions: read
  contents: write

jobs:
  status_fpm:
    if: ${{ always() && (github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule') && !contains(github.event.head_commit.message, '[skip ci]') }}
    name: Generate STATUS.md
    runs-on: ubuntu-latest
    steps:
      - name: Generate summary
        uses: gha3mi/setup-fortran-conda@dev
        with:
          generate-status-fpm: true
